#!/bin/sh

autostart() {
    rm -f /tmp/.X11-unix/X0 /tmp/.X0-lock
    xauth add :1 . $(od -An -N16 -tx1 /dev/urandom | tr -d ' \n')
    Xwayland :1 -auth ~/.Xauthority -nolisten tcp -rootless &
    swaybg -i ~/Pictures/wallpapers/1293302.jpg -m center -c 928374 &
    swaync &
    somebar &
    someblocks &
    dbus-update-activation-environment --systemd DISPLAY=:1 XAUTHORITY=~/.Xauthority

    # Signal someblocks on volume change (signal 2)
    pactl subscribe 2>/dev/null | grep --line-buffered "sink" | \
        while read -r _; do pkill -RTMIN+2 someblocks 2>/dev/null; done &

    # Signal someblocks on media change (signal 3)
    playerctl -F status 2>/dev/null | \
        while read -r _; do pkill -RTMIN+3 someblocks 2>/dev/null; done &

    # Signal someblocks on notification change (signal 4)
    swaync-client --subscribe 2>/dev/null | \
        while read -r _; do pkill -RTMIN+4 someblocks 2>/dev/null; done &
}

exec dwl -s "$(declare -f autostart); autostart" "$@"
